### PR TITLE
Add resize argument, various fixes

### PR DESCRIPTION
**Pull request by Maw-Fox**
### **Features:**
- Implement automagic and optional `--resize` argument (boolean) to allow people to use not previously-prepared datasets more easily and perform the associated scaling and cropping as necessary to match the best-fitting bucket. Defaults to `False`.

### **Fixes:**
- Windows users require explicit UTF-8 declaration for file read, in particular for e6 captions.
- Convert to RGB 3-channel, anything fed into `collate_fn` that hasn't been normalized in this way will cause a `torch.Size` discrepancy. E.g: `torch.Size([3, 512, 512])`, `torch.Size([4, 512, 512])`
- Make hinted type returns **a little** more accurate, and fix relevant documentation.
- Revert to Tuple[int, int, int] (idx, w, h) as implemented in @hasuwoof 's bucketing implementation. This allows us to perform resizing in the appropriate method.

### CODE REVIEW

**Comment by Maw-Fox** [comment]
There **may** be an issue that wasn't found during preliminary tests, I am going to close this current pull request until I can manage to make sure this issue is unrelated to these commits.

**Comment by harubaru** [comment]
What's the issue?

**Comment by Maw-Fox** [comment]
> What's the issue?

Not sure yet, still trying to figure out what is happening on their end, it could be a variety of factors but it's likely not this code (just making sure that it isn't before I opt to pull req something that could potentially break things with little-to-no error reporting regarding it).

Seems to be freezing up and not progressing for them, but allegedly it works with 1:1 512x512 images.

**Comment by Maw-Fox** [comment]
Seems to be working for someone else though after some more testing so chalking it up to the other person's environment.

**Comment by Maw-Fox** [comment]
Fix for future depreciation in pillow. [docs](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Resampling)

**Pull request merged**
