### PR TITLE
Code overhaul & relicense to AGPL 3.0

### PR DESCRIPTION
**Pull request by harubaru**

### CODE REVIEW

**Comment by harubaru** [comment]
I have been considering on relicensing the newer codebase to AGPL 3.0 to help keep this work open-source while also simultaneously removing all of the prior CompVis code.

CC Board:
- [X] @harubaru
- [ ] @cafeai
- [ ] @MoonShinkiro
- [ ] @arbizoZoren
- [ ] @koukuno
- [ ] @soup6020

CC Codebase Contributors:
- [ ] @Maw-Fox
- [ ] @AstraliteHeart
- [ ] @chavinlo
- [ ] @laksjdjf
- [ ] @hasuwoof
- [ ] @john-sungjin

**Comment by arbizoZoren** [comment]
Sure.

**Comment by chavinlo** [comment]
I consent

**Comment by MoonShinkiro** [comment]
I consent with the terms.

**Comment by koukuno** [comment]
I consent

**Comment by laksjdjf** [comment]
I consent

**Comment by john-sungjin** [comment]
I consent as well.

**Comment by AstraliteHeart** [comment]
I consent

**Comment by cafeai** [comment]
i consent!

**Comment by hasuwoof** [comment]
LGTM

**Comment by soup6020** [comment]
Agreed

**Comment by Maw-Fox** [comment]
I consent

**Pull request merged**
